pipeline {
    agent { label 'gradle-agent' }
    stages {
        stage('Compile') {
            steps {
                sh """
                  cd Chapter08/sample1
                  chmod +x gradlew
                  ./gradlew compileJava
                """
            }
        }
        stage('Unit test') {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew test
                """
            }
        }
        stage('Code coverage') {
            when { branch 'master' }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew jacocoTestCoverageVerification
                """
            }
        }
        stage('Static code analysis') {
            when {
                anyOf {
                    branch 'master'
                    branch pattern: '.*feature.*', comparator: 'REGEXP'
                }
            }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew checkstyleMain
                """
            }
        }
    }
    post {
        always {
            sh """
              cd Chapter08/sample1
              ./gradlew jacocoTestReport
            """
        }
        success {
            echo "tests pass!"
        }
        failure {
            echo "tests fail!"
        }
    }
}
