pipeline {
    agent { label 'gradle-agent' }
    environment {
        GRADLE_USER_HOME = '/home/jenkins/.gradle'
    }
    stages {
        stage('Compile') {
            steps {
                sh """
                  cd Chapter08/sample1
                  chmod +x gradlew
                  ./gradlew compileJava
                """
            }
        }
        stage('Unit test') {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew test
                """
            }
        }
        stage('Code coverage') {
            when { branch 'master' }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew jacocoTestReport
                  ./gradlew jacocoTestCoverageVerification
                """
            }
        }
        stage('Static code analysis') {
            when {
                anyOf {
                    branch 'master'
                    branch pattern: '.*feature.*', comparator: 'REGEXP'
                }
            }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew checkstyleMain
                """
            }
        }
        stage('Invalid branch') {
            when {
                not {
                    anyOf {
                        branch 'master'
                        branch pattern: '.*feature.*', comparator: 'REGEXP'
                    }
                }
            }
            steps {
                error "Pipeline failed: branch '${env.BRANCH_NAME}' is not master or a feature branch!"
            }
        }
    }
    post {
        success {
            echo "pipeline ran perfectly"
        }
        failure {
            echo "pipeline failure"
        }
    }
}
