pipeline {
    agent { label 'gradle-agent' }
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('Check README Changes') {
            when {
                changeset "**/README.md"
            }
            steps {
                echo "README file changed"
            }
        }
        stage("Compile") {
            steps {
                sh "./gradlew compileJava"
            }
        }
        stage("Unit test") {
            steps {
                sh "./gradlew test"
            }
        }
        stage("Code coverage") {
            steps {
                sh "./gradlew jacocoTestReport"
                sh "./gradlew jacocoTestCoverageVerification"
            }
        }
        stage("Static code analysis") {
            steps {
                sh "./gradlew checkstyleMain"
            }
        }
    }
    post {
        success {
            echo 'All tests passed!'
        }
        failure {
            echo 'Build or tests failed, sending notification...'
        }
    }
}
