pipeline {
    agent { label 'gradle-agent' }
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage("Compile") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew compileJava
                """
            }
        }
        stage("Unit test") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew test
                """
            }
        }
        stage("Code coverage") {
            when {
                changeset "**/*.java"
            }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew jacocoTestReport
                  ./gradlew jacocoTestCoverageVerification
                """
            }
        }
        stage("Static code analysis") {
            when {
                changeset "**/*.java"
            }
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew checkstyleMain
                """
            }
        }
    }
    post {
        success {
            echo "pipeline ran perfectly"
        }
        failure {
            echo "pipeline failure"
        }
    }
}
