pipeline {
    agent { label 'gradle-agent' }
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('Check README Changes') {
            when {
                changeset "**/README.md"
            }
            steps {
                echo "README file changed"
            }
        }
        stage("Compile") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew compileJava
                """
            }
        }
        stage("Unit test") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew test
                """
            }
        }
        stage("Code coverage") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew jacocoTestReport
                  ./gradlew jacocoTestCoverageVerification
                """
            }
        }
        stage("Static code analysis") {
            steps {
                sh """
                  cd Chapter08/sample1
                  ./gradlew checkstyleMain
                """
            }
        }
    }
    post {
        success {
            echo 'All tests passed!'
        }
        failure {
            echo 'Build or tests failed, sending notification...'
        }
    }
}
